Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.ssh.insert_key = false

  config.vm.define "db" do |db|
    db.vm.hostname = "db.local"
    db.vm.network "private_network", ip: "192.168.56.11"
    db.vm.provider "virtualbox" do |vb|
      vb.name = "COGSI_DB_VM"
      vb.memory = 1024
      vb.cpus = 1
    end

    db.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/playbook-db.yml"
      ansible.inventory_path = "ansible/inventory.ini"
    end
  end

  config.vm.define "app" do |app|
    app.vm.hostname = "app.local"
    app.vm.network "private_network", ip: "192.168.56.10"
    app.vm.provider "virtualbox" do |vb|
      vb.name = "COGSI_APP_VM"
      vb.memory = 2048
      vb.cpus = 2
    end

    app.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/playbook-app.yml"
      ansible.inventory_path = "ansible/inventory.ini"
    end
  end
end
